### ISSUE TITLE
Equipment manager section

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/toby#178]
I would like to have a brand new section in Toby: equipment manager. It should be composed from at least two sections:
* list of all equipment in the company (visible only for administrators), incl. unique ID code, label, nullable assigned person and probably some dates (added to inventory at, assigned to person at)
* list of all equipment assigned to selected person (administator should be able to select a person; authenticated employee should see only his/her assigned products)

I would like to index all laptops, monitors, peripherals and stuff in the company.

**Comment by EwelinaSkrzypacz** [comment]
Clarifications: 

- We will have a label printer - there will be stickers with barcodes and some number.
- We will sign an equipment entrustment agreement - that's why each piece of equipment must be identifiable (e.g., no. 000001, a description field, where we'll write something like: "TV brand X, model Y, etc.") + the ability to assign a person (but not always, because we'll assign someone to a laptop, but not necessarily to a TV) and whether the equipment is portable (taken out of the office).
- The equipment list should be exportable to PDF.
- A new role needs to be added - warehouse manager.
- We need to consider whether we also want to keep software licenses, e.g., for PhpStorm, in the system - after all, this is also company property.
- Data import from Excel - to make it easier to enter a lot of data for the first time.
